### ISSUE TITLE
# command-line-arguments ./main.go:49:15: undefined: loadSpreadSheet

### ISSUE THREAD

**Issue by AkshayRameshAppDEV** [bleeding182/localization#3]
1. I have created my credentials from Google API services and copy pasted the contents from credentials.json(Sheets API enabed)
2. I made copy of the example google sheets provided by you in the example and gave read and edit permission.(New sheetID:1GmVML6b4sxQqCf8HmWuZYAdtlOScS5QUc9QTWGBVhRU)
3. I run the below code from the localization folder:
`go run main.go --sheetID 1GmVML6b4sxQqCf8HmWuZYAdtlOScS5QUc9QTWGBVhRU android`

4. I am getting `# command-line-arguments
./main.go:49:15: undefined: loadSpreadSheet`

Can you please tell me if I am missing any steps or should I run a different command to achieve the exports folder result?

Thank You

**Comment by bleeding182** [comment]
Hi!

> I have created my credentials from Google API services and copy pasted the contents from credentials.json(Sheets API enabed)

This tool is currently using the OAuth API. It will print a link to open in your browser when you run it for the first time where you get a code to copy/paste after authenticating. I'm not sure what you're doing with the credentials.json. I follow the [quickstart from the documentation](https://developers.google.com/sheets/api/quickstart/go) if you'd like to take a look.

> I made copy of the example google sheets provided by you in the example and gave read and edit permission.(New sheetID:1GmVML6b4sxQqCf8HmWuZYAdtlOScS5QUc9QTWGBVhRU)

You should be able to access your own documents if you authenticate with OAuth. The example is publicly available as a demo. You shouldn't need to share your file with others unless you want to grant them access

> I run the below code from the localization folder:
`go run main.go --sheetID 1GmVML6b4sxQqCf8HmWuZYAdtlOScS5QUc9QTWGBVhRU android`

You should run `go build` then run the executable from the `/bin` folder. Alternatively you can use `go run .` (or list all of the `.go` files)

**Comment by AkshayRameshAppDEV** [comment]
Thank you for the detailed information.

1. I ran from `go build` first from the localization folder(which created the executable called **localization**), 
2. Next, `./localization --sheetID 1upHiDHWu5m30tYdhMDP4GXheOWUE4r3VrHfmAUXiuyI android`
3. Copy paste the link from console to browser and get authorization code.
4. Copy paste the authorization code in the console and hit enter.
5. Program will execute and export folder will be created with string files.

Thanks once again for the help @bleeding182. Appreciate it.
